export const COLORS = {
  // options
  RED: '#FFADAD',
  ORANGE: '#FFD6A5',
  YELLOW: '#FDFFB6',
  GREEN: '#CAFFBF',
  BLUE: '#9BF6FF',
  NAVY: '#A0C4FF',
  PURPLE: '#BDB2FF',
  PINK: '#FFC6FF',

  // app
  GRAY: '#CFCFCF',
  ELECTRIC_BLUE: '#0099ff',
} as const;

export const COLOR_OPTIONS = [
  COLORS.RED,
  COLORS.YELLOW,
  COLORS.BLUE,
  COLORS.GREEN,
  COLORS.ORANGE,
  COLORS.NAVY,
  COLORS.PURPLE,
  COLORS.PINK,
];
